### ISSUE TITLE
Not working for iOS chat logs (different format)

### ISSUE THREAD

**Issue by marc1404** [ristri/whatsappstat#1]
Found this tool on EchoJS and wanted to try it out, sadly it does not work when I try to upload chats exported from the WhatsApp iOS version:
```
Uncaught TypeError: Cannot read property 'forEach' of null
    at FileReader.fileReader.onload (script.min.js:2)
```
I suspect the problem stemming from the extraction of sender names:
```javascript
var sender = fileReader.result.match(/[-](\s\w+)+[:]/g);
```
The RegEx is looking for the sender's name consisting of normal characters enclosed by a dash and colon.
However, iOS chat logs enclose the date within brackets `[ ]`.
Example:
`[11.10.16, 13:45:15] Firstname Lastname:`
Additionally, if I decide to use e.g. Emojis in my contacts names `\w` will fail to recognize the sender's name as well.

**Comment by ristri** [comment]
I have modified the RegEx. Now It should work.
`` [-](\s\w+)+[:]`` to ``[-\]](\s\w+)+[:]``  
`` (\d+\/\d+\/\d+)([^-])`` to ``(\d+[\/.]\d+[\/.]\d+)([^-\]]*)``
